### ISSUE TITLE
STYLE   GEOMTRANSFORM 'labelcenter'

### ISSUE THREAD

**Issue by LarsSchy** [geographika/mappyfile#119]
The STYLE - GEOMTRANSFORM can have the option: 'labelcenter'.   Trying to figure out how it works today and what the difference is to the other options.  
It is in the documentation: https://mapserver.org/mapfile/label.html 

It seems like this option was added in 7.2  https://github.com/MapServer/MapServer/commit/ee0462269cfcf5b13ce18a949533066e1aac632e

**Comment by geographika** [comment]
Interesting!

[labelcenter](See https://mapserver.org/mapfile/label.html#mapfile-label-geomtransform) is allowed in a `STYLE` but only when the `STYLE` is part of a `LABEL` not a `CLASS`. 

It is not an option listed in the [STYLE](https://mapserver.org/mapfile/style.html#mapfile-style-geomtransform) docs. 

mappyfile currently reuses the [style.json](https://github.com/geographika/mappyfile/blob/master/mappyfile/schemas/style.json) schema for styles in both a `CLASS` and a `LABEL`. 

The easiest fix would be to add `labelcenter` as an allowed keyword to style.json, but this show as valid if used in a `CLASS`. 
Does MapServer crash if `labelcenter` is used in a `CLASS` `STYLE` rather than a `LABEL` `STYLE`?

**Comment by geographika** [comment]
Fixed with https://github.com/geographika/mappyfile/commit/95877c1231d71f7e56d4a1b6cb32315e74bfb2fb

It seems this was missing from the docs when I first added the styyle.json schema. See https://github.com/MapServer/MapServer/issues/6219

It is also missing from the MapServer msautotests.
