### ISSUE TITLE
Incudes fail on windows

### ISSUE THREAD

**Issue by ianturton** [geographika/mappyfile#55]
When parsing a map file with includes on windows, parsing fails as it looks in the parent directory instead of the current one,

Fixed by https://github.com/geographika/mappyfile/pull/54

**Comment by geographika** [comment]
Thanks for spotting this. I presume this only happened when parsing a string rather than a file (which would use the Mapfile path as the root and was tested for)?

I have recreated and created a unit test for this, and used os.sep rather than backslash as in the pull request, so this should now be fixed in master. 

Is it ok to add you to the contributors list?

**Comment by ianturton** [comment]
On Mon, 11 Jun 2018 at 13:03, Seth G <notifications@github.com> wrote:

> Thanks for spotting this. I presume this only happened when parsing a
> string rather than a file (which would use the Mapfile path as the root and
> was tested for)?
>
>
Yes, that would be it.


> I have recreated and created a unit test for this, and used os.sep rather
> than backslash as in the pull request, so this should now be fixed in
> master.
>

Thanks


> Is it ok to add you to the contributors list?
>

Sure

Thanks

Ian

**Comment by geographika** [comment]
Fixed in the latest 0.7.1 release
